import type { Bone } from '../types/bone';
import { boneSvg, icon } from './icons';

export function generalInfoMarkup() {
  return `<div class="detail-visual">${boneSvg}</div><div class="detail-body general-body"><div class="detail-region">Sistema esquelético</div><h2>El cuerpo humano</h2><div class="info lead"><h3>Una arquitectura viva</h3><p>El esqueleto sostiene el cuerpo, protege los órganos y trabaja con músculos y articulaciones para producir movimiento.</p></div><div class="info"><h3>En números</h3><div class="mini-stats"><div><strong>206</strong><span>huesos en el adulto</span></div><div><strong>≈14%</strong><span>del peso corporal</span></div><div><strong>Fémur</strong><span>el más largo</span></div><div><strong>Estribo</strong><span>el más pequeño</span></div></div></div><div class="info"><h3>Cómo se organiza</h3><div class="system-split"><div><strong>Axial <em>≈80</em></strong><p>Cráneo, columna, costillas y esternón: el eje central del cuerpo.</p></div><div><strong>Apendicular <em>≈126</em></strong><p>Brazos, piernas y cinturas: permite interactuar con el entorno.</p></div></div></div><div class="info"><h3>Funciones principales</h3><div class="function-list"><div>${icon('shield')}<p><strong>Protección</strong><span>Resguarda el cerebro, corazón, pulmones y otros órganos vitales.</span></p></div><div>${icon('support')}<p><strong>Soporte</strong><span>Sostiene el peso del cuerpo y define su forma.</span></p></div><div>${icon('activity')}<p><strong>Movimiento</strong><span>Forma palancas junto a músculos y articulaciones.</span></p></div><div>${icon('mineral')}<p><strong>Minerales</strong><span>Almacena calcio y fósforo para el organismo.</span></p></div><div>${icon('blood')}<p><strong>Hematopoyesis</strong><span>La médula produce células de la sangre.</span></p></div></div></div></div>`;
}

export function jogButtonMarkup() {
  return `<button class="jog-btn" type="button" aria-label="Activar modo trotar" aria-pressed="false" disabled>${icon('activity')}<span>Trotar</span></button>`;
}

export function gravityButtonMarkup() {
  return `<button class="gravity-btn" type="button" aria-label="Activar gravedad" title="Activar gravedad" aria-pressed="false" disabled>${icon('skull')}</button>`;
}

export function infoModalMarkup() {
  return `<div class="info-modal" aria-hidden="true"><section class="info-dialog" role="dialog" aria-modal="true" aria-labelledby="info-title"><button class="info-close" type="button" aria-label="Cerrar información">${icon('close')}</button><div class="info-dialog-head"><div class="detail-region">Acerca del atlas</div><h2 id="info-title">Atlas Óseo</h2><p>Un explorador anatómico 3D del esqueleto humano completo — 204 huesos navegables, cada uno con su propia ficha. Hacé click en cualquier hueso, en el modelo o en el listado para conocerlo.</p></div><div class="info-dialog-section"><h3>Cómo navegar</h3><div class="command-table" role="table" aria-label="Comandos de navegación"><div class="command-row command-head" role="row"><span role="columnheader">Acción</span><span role="columnheader">Resultado</span></div><div class="command-row" role="row"><strong role="cell">Click en un hueso</strong><span role="cell">Abre su ficha y hace zoom</span></div><div class="command-row" role="row"><strong role="cell">Esc</strong><span role="cell">Cierra la ficha actual</span></div><div class="command-row" role="row"><strong role="cell">Arrastrar</strong><span role="cell">Mueve el modelo</span></div><div class="command-row" role="row"><strong role="cell">Scroll / pinch</strong><span role="cell">Acerca o aleja</span></div><div class="command-row" role="row"><strong role="cell">Doble click / doble tap</strong><span role="cell">Acerca al punto señalado</span></div><div class="command-row" role="row"><strong role="cell">Cmd / Ctrl + arrastrar</strong><span role="cell">Rota el modelo</span></div><div class="command-row" role="row"><strong role="cell">Click en espacio vacío</strong><span role="cell">Vuelve a la vista general</span></div></div></div><div class="info-dialog-section"><h3>Fuentes y créditos</h3><p>Modelo 3D basado en <a href="https://anatomytool.org/content/open3dmodel-skeleton-english-labels" target="_blank" rel="noopener noreferrer">“Open3DModel — Skeleton — English labels”</a>, por Open3D project, George J.R. Maat (LUMC), Eungyeol Lee (LUMC) et al., bajo licencia <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener noreferrer">CC BY-SA</a>. Adaptado para esta experiencia interactiva.</p><p>Contenido anatómico compilado a partir de fuentes de anatomía humana de referencia general.</p></div><div class="info-dialog-section"><h3>Sobre este proyecto</h3><p>Atlas Óseo es un proyecto personal construido con TypeScript, Three.js, WebGL y Vite. Es una pieza de portfolio, no material médico certificado, pensado para aprender y explorar, no como referencia clínica.</p></div><footer class="info-author"><span>Hecho por</span><strong>Agustín D'Elía</strong><div><a href="https://x.com/agusrdelia/" target="_blank" rel="noopener noreferrer">X / Twitter</a><a href="https://www.linkedin.com/in/agusrdelia/" target="_blank" rel="noopener noreferrer">LinkedIn</a></div></footer></section></div>`;
}

export function mobileRotationCommandMarkup() {
  return `<div class="command-row" role="row"><strong role="cell">Dos dedos (mobile)</strong><span role="cell">Rota el modelo</span></div>`;
}

export function audioCreditMarkup() {
  return `<p>Música y efectos de sonido obtenidos de <a href="https://pixabay.com/" target="_blank" rel="noopener noreferrer">Pixabay</a>.</p>`;
}

export function modelCreditMarkup() {
  return `<a href="https://anatomytool.org/content/open3dmodel-skeleton-english-labels" target="_blank" rel="noopener noreferrer">“Open3DModel - Skeleton- English labels”</a> by <a href="https://anatomytool.org/open3Dmodel-about" target="_blank" rel="noopener noreferrer">Open3D project</a>, <a href="https://www.researchgate.net/profile/George-Maat" target="_blank" rel="noopener noreferrer">George J.R. Maat</a>, LUMC, <a href="https://www.eungyeol-lee.com/" target="_blank" rel="noopener noreferrer">Eungyeol Lee</a>, LUMC et al, license: <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener noreferrer">CC BY-SA</a>. Adaptado para esta experiencia interactiva.`;
}

export function appMarkup(generalInfo: string) {
  return `<main class="shell app-loading"><aside class="sidebar"><button class="sidebar-close" type="button" aria-label="Cerrar listado">${icon('close')}</button><header class="brand"><div class="eyebrow">Anatomía</div><h1>Explora el cuerpo,<br><i>hueso a hueso.</i></h1><p>Selecciona cualquier estructura para conocer su función y relaciones anatómicas.</p></header><div class="search-wrap">${icon('search')}<input id="search" type="search" placeholder="Buscar un hueso..." aria-label="Buscar un hueso"><button class="collapse-all" aria-label="Expandir todas las categorías" title="Expandir o colapsar categorías">${icon('collapse')}</button></div><nav class="bone-list" aria-label="Listado de huesos"></nav><footer class="progress"><div class="progress-head"><span>Tu exploración</span><strong class="progress-percent">0%</strong></div><div class="progress-track"><i></i></div><p><strong class="viewed-count">0</strong> de <span class="total-count">204</span> huesos descubiertos</p></footer></aside><button class="sidebar-backdrop" type="button" aria-label="Cerrar listado" tabindex="-1"></button><section class="viewport"><button class="mobile-nav" aria-label="Abrir listado" aria-expanded="false">${icon('menu')}</button><div class="topbar"><div></div><div class="actions"><button class="dance-btn" type="button" aria-label="Activar modo baile" aria-pressed="false" disabled>${icon('music')}<span>Bailar</span></button><button class="reset-btn desktop-reset" aria-label="Restablecer vista">${icon('reset')}Reset</button><button class="icon-btn" aria-label="Información">${icon('info')}</button></div></div><canvas id="scene" aria-label="Modelo tridimensional navegable del esqueleto humano"></canvas><div class="control-guide"><span>${icon('rotate')}<b>Arrastrar</b> Mover</span><span>${icon('zoom')}<b>Scroll</b> Zoom</span><span>${icon('move')}<b>Cmd / Ctrl</b> Rotar</span></div><div class="mobile-control-guide" aria-label="Controles táctiles"><span>${icon('touch-one')}<b>Mover</b></span><span>${icon('touch-two')}<b>Rotar</b></span><span>${icon('pinch')}<b>Zoom</b></span></div><div class="loader"><i></i><strong>Generando estructura ósea</strong></div><aside class="detail" aria-live="polite">${generalInfo}</aside></section></main><div class="tooltip"></div>`;
}

export function boneDetailMarkup(b: Bone, image: string) {
  const links = b.articulations?.length
    ? b.articulations
        .map(
          (a) =>
            `<button class="articulation-link" data-target="${a.target}"><strong>${a.label}</strong><span>${a.detail}</span>${icon('chevron')}</button>`
        )
        .join('')
    : '<p>Relaciones anatómicas en revisión.</p>';
  return `<header class="detail-sheet-header"><button class="detail-sheet-drag" type="button" aria-label="Expandir o contraer ficha"><i></i></button><div class="detail-sheet-title"><span>${b.region}</span><strong>${b.name}</strong></div><button class="close" aria-label="Cerrar">${icon('close')}</button></header><div class="detail-visual"><img class="bone-render" src="${image}" alt="Vista aislada de ${b.name}"></div><div class="detail-body"><div class="detail-region">${b.region}</div><h2>${b.name}</h2><div class="latin">${b.latin}</div><div class="quick-grid"><div><span>Tipo</span><strong>${b.type}</strong></div><div><span>Lateralidad</span><strong>${b.laterality || 'Impar'}</strong></div><div class="wide"><span>Ubicación</span><strong>${b.location}</strong></div></div>${b.formation ? `<div class="formation"><span>Formación</span><p>${b.formation}</p></div>` : ''}<div class="info"><h3>Función y anatomía</h3><p>${b.fact}</p></div><div class="info"><h3>Se articula con</h3><div class="articulation-list">${links}</div></div>${b.curiosity ? `<div class="curiosity"><span>¿Sabías que?</span><p>${b.curiosity}</p></div>` : ''}</div>`;
}
